title: Araz swandy
logo: "/images/logo.png?raw=true"
description: > #
  **Junior Python Developer - Focus on Data Engineering**
  <br><br>
  Hi, I'm Araz Swandy, a Junior Python Developer from Indonesia. 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-theme-minimal
